### ISSUE TITLE
Automated tests

### ISSUE THREAD

**Issue by osorensen** [ramiyaari/simode#3]
One of the points on my [review checklist](https://github.com/openjournals/joss-reviews/issues/1850) asks:

> Are there automated tests or manual steps described so that the functionality of the software can be verified?

I am not able to find any such tests in this package. I suggest adding unit tests using the `devtools` package. A good place to start is reading [this chapter](http://r-pkgs.had.co.nz/tests.html).

**Comment by ramiyaari** [comment]
There are demos as part of the package which you can run.
To see the avaliable demos type: demo(package='simode')
To run a demo type: demo(<demo_name>,package='simode')
Is this not good enough for automated tests?

**Comment by osorensen** [comment]
The demos do a great job in demonstrating how to use the package, but will they fail if a subtle bug causes one of the package functions to return the wrong answer, but without issuing an error or warning?

When reading the point on the review checklist, I had in mind something like the following example. I have taken most of the code from the example to the function `simode()`, but added some lines at the bottom showing how one could test the numerical output from the function. As far as I can see, the demos do not have any verification that the numbers coming out are correct.

```r
library(simode)

######## THE FOLLOWING LINES ARE TAKEN FROM THE EXAMPLE TO SIMODE() ########
## generate model equations and parameters (X=Prey,Y=Predator)
pars <- c('alpha','beta','gamma','delta')
vars <- c('X','Y')
eq_X <- 'alpha*X-beta*X*Y'
eq_Y <- 'delta*X*Y-gamma*Y'
equations <- c(eq_X,eq_Y)
names(equations) <- vars
x0 <- c(0.9,0.9)
names(x0) <- vars
theta <- c(2/3,4/3,1,1)
names(theta) <- pars

## generate observations
n <- 50
time <- seq(0,25,length.out=n)
model_out <- solve_ode(equations,theta,x0,time)
x_det <- model_out[,vars]
set.seed(1000)
sigma <- 0.05
obs <- list()
for(i in 1:length(vars)) {
  obs[[i]] <- pmax(0, rnorm(n,x_det[,i],sigma))
}
names(obs) <- vars

## estimate model parameters with known initial conditions
simode_fit1 <- simode(equations=equations, pars=pars, fixed=x0, time=time, obs=obs)


######## THE FOLLOWING LINES SHOW HOW ONE COULD PERFORM UNIT TESTING OF THE SIMODE() FUNCTION ########
testthat::test_that("simode returns correct answers",{
  testthat::expect_equal(round(simode_fit1$nls_loss, 5), 0.24645)
  testthat::expect_equal(as.numeric(round(simode_fit1$nls_sol[50, ], 5)), c(0.56900, 0.63472 ))
}
)
```

Whether this type of testing is necessary or not depends on how one interprets the point on the reviewer checkelist. Perhaps editor @mjsottile could clarify if demos are sufficient?

**Comment by ramiyaari** [comment]
I will look into it...

**Comment by mjsottile** [comment]
Based on the guidance in the JOSS documentation, the testing aspect reads as follows:

Authors are strongly encouraged to include an automated test suite covering the core functionality of their software.

- **Good**: An automated test suite hooked up to an external service such as Travis-CI or similar
- **OK**: Documented manual steps that can be followed to objectively check the expected functionality of the software (e.g., a sample input file to assert behavior)
- **Bad (not acceptable)**: No way for you the reviewer to objectively assess whether the software works

I would interpret the demos included in the package as falling in between the second bullet and the third - "OK" and "Bad".  On the OK side, they do serve the role of demonstrating how the code works, and represent as basic set of specific test cases that can be run manually.  On the Bad side, my browsing of the code doesn't show that the user has any way to assess what a correct output is, so they cannot assess whether or not the code executed correctly or not.  They can only observe the code executing and producing some output - correct or not.

I agree with @osorensen - the devtools package does provide some basic mechanisms for automatically running tests, including automatic assessment of whether they should be considered passing or not passing.  I would recommend adapting the demos to be usable through that mechanism.  I would also recommend improving the documentation in the demos if they are intended to be usable as tests to clearly articulate what the expected result of running the code should be.

**Comment by ramiyaari** [comment]
OK, I will work on adding automated tests soon

**Comment by ramiyaari** [comment]
OK @osorensen  and @mjsottile , I've added unit test using testthat to the package

**Comment by osorensen** [comment]
Thanks, I think the tests look very satisfactory. I do however get a warning when testing the package, caused by the following lines in `test_simode_argument.R`

```
obs <- list()
obs['X'] <- 1:10
obs['Y'] <- 10:1
```

If the assignments are changed to the following, everything will work fine, so please do that.

```
obs <- list()
obs['X'] <- 1:10
obs['Y'] <- 10:1
```

**Comment by ramiyaari** [comment]
@whedon generate pdf

**Comment by ramiyaari** [comment]
Thanks, I've fixed the test file (plus fixed a problem I found on the way in the code).

**Comment by mjsottile** [comment]
@osorensen are you satisfied that the test issue is addressed for the review to proceed forward?

**Comment by osorensen** [comment]
Yes, @mjsottile .

**Comment by ramiyaari** [comment]
So, I'm closing this issue: @osorensen , @mjsottile ...
