### ISSUE TITLE
Community guidelines

### ISSUE THREAD

**Issue by osorensen** [ramiyaari/simode#4]
Considering the following point on the [review checklist](https://github.com/openjournals/joss-reviews/issues/1850) for JOSS:

> Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

Please add a note about how to do this, either as part of the README file, or as a separate file in the repository.

**Comment by ramiyaari** [comment]
Hi @osorensen , regarding this point, we are not sure exactly what should be added to the README as we are not aware of the standard practices on github. We thought that the fact the project is on github and with the license that we've supplied means that anyone could use it and download the code and make changes. It would be great if anybody would want to build on this project and contribute to it. What is the standard way to reflect that? Do you have any example from a different project?

**Comment by osorensen** [comment]
I agree with you that being on GitHub should be sufficient. This is fine with me.

**Comment by osorensen** [comment]
@ramiyaari , in my own package `hdme`, which was published in JOSS, I added the following section to the GitHub readme. Feel free to use it: https://github.com/osorensen/hdme#contributions

**Comment by ramiyaari** [comment]
@osorensen, thankyou very much. I've updated the simode readme accordingly.
